name: mlpipeline

channels:
        - defaults
dependencies:
        - python=3.8
        - pip
        - pip:
                - mlflow        >= 1.0
                - entrypoints   >= 0.3
                - wget          >= 3.2
                - aenum         >= 2.2.6
                - dvc           >= 2.9.3
                - PyYAML        >= 6.0
                - nbconvert     >= 6.4.1
                - nbformat      >= 5.1.3
                - matplotlib    >= 3.5.1
                - matplotlib-inline     >= 0.1.3
                - nest-asyncio  >= 1.5.4
                - pandas        >= 1.3.5
                - scikit-learn  >= 1.0.2
                - scipy         >= 1.7.3
                - great-expectations    >= 0.14.4
                - gremlinpython >= 3.5.0
                - wget          >= 3.2
                - numpy         >= 1.21.1
                - seaborn       >= 0.11.2
                - tqdm          >= 4.62.3
                - watermark     >= 2.3.0
